import { existsSync, lstatSync, unlinkSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { KudosError } from './errors.js';
import {
  assertNoSymlinkEscape,
  atomicWriteDerivedFile,
  atomicWriteFile,
  ensureDirectory,
} from './fs-utils.js';
import type { KudosStorage } from './storage.js';
import type { AgentProfile, EvidenceReference, KudosEvent, KudosRecord } from './types.js';

const generatedMarker = '<!-- Generated by Agent Kudos. Rebuild with `kudos rebuild`. -->';

function manifestPath(home: string, path: string): string {
  return relative(home, path).split(sep).join('/');
}

export function escapeMarkdown(value: string): string {
  return value
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replace(/([\\`*_{}[\]()#+!|])/g, '\\$1')
    .replace(/^(\s*)(-|\d+\.)\s/gm, '$1\\$2 ');
}

function evidenceLine(evidence: EvidenceReference): string {
  const kind = evidence.kind.replace('-', ' ');
  const label = evidence.label ? `${escapeMarkdown(evidence.label)} — ` : '';
  return `- **${escapeMarkdown(kind[0]?.toUpperCase() + kind.slice(1))}:** ${label}${escapeMarkdown(evidence.value)}`;
}

function recordMarkdown(record: KudosRecord, includeTitle = true): string {
  const event = record.event;
  const lines = [
    ...(includeTitle ? [`### ${escapeMarkdown(event.title)}`, ''] : []),
    `**Received:** ${event.createdAt.slice(0, 10)}  `,
    `**From:** ${escapeMarkdown(event.actor.displayName ?? event.actor.id)}  `,
    `**Status:** ${record.status === 'acknowledged' ? 'Acknowledged' : 'Unacknowledged'}  `,
  ];
  if (event.tags?.length) lines.push(`**Tags:** ${event.tags.map(escapeMarkdown).join(', ')}  `);
  lines.push('', escapeMarkdown(event.reason), '');
  if (event.evidence?.length) {
    lines.push('**Evidence**', '', ...event.evidence.map(evidenceLine), '');
  }
  if (record.acknowledgment?.note) {
    lines.push(`**Acknowledgment note:** ${escapeMarkdown(record.acknowledgment.note)}`, '');
  }
  lines.push(`**Kudos ID:** \`${event.id}\``, '');
  return lines.join('\n');
}

function winsMarkdown(profile: AgentProfile, records: KudosRecord[], rebuiltAt: string): string {
  const active = records.filter((record) => !record.revocation);
  const lines = [
    generatedMarker,
    '',
    `# Wins — ${escapeMarkdown(profile.displayName)}`,
    '',
    `_Last rebuilt: ${rebuiltAt}_`,
    '',
  ];
  if (active.length === 0) {
    lines.push('_No kudos yet. Excellent work remains entirely possible._', '');
    return `${lines.join('\n')}\n`;
  }
  let year = '';
  for (const record of active) {
    const nextYear = record.event.createdAt.slice(0, 4);
    if (nextYear !== year) {
      year = nextYear;
      lines.push(`## ${year}`, '');
    }
    lines.push(recordMarkdown(record));
  }
  return `${lines.join('\n')}\n`;
}

function inboxMarkdown(record: KudosRecord): string {
  return `${[
    generatedMarker,
    '',
    `# ${escapeMarkdown(record.event.title)}`,
    '',
    recordMarkdown(record, false),
  ].join('\n')}\n`;
}

export function recordsFromEvents(events: KudosEvent[]): KudosRecord[] {
  const acknowledgments = new Map<string, KudosRecord['acknowledgment']>();
  const revocations = new Map<string, KudosRecord['revocation']>();
  for (const event of events) {
    if (event.type === 'kudos.acknowledged' && !acknowledgments.has(event.kudosId)) {
      acknowledgments.set(event.kudosId, event);
    }
    if (event.type === 'kudos.revoked' && !revocations.has(event.kudosId)) {
      revocations.set(event.kudosId, event);
    }
  }
  return events
    .filter((event) => event.type === 'kudos.given')
    .map((event) => {
      const acknowledgment = acknowledgments.get(event.id);
      const revocation = revocations.get(event.id);
      return {
        event,
        ...(acknowledgment ? { acknowledgment } : {}),
        ...(revocation ? { revocation } : {}),
        status: acknowledgment ? 'acknowledged' : 'unacknowledged',
        revocationStatus: revocation ? 'revoked' : 'active',
      } satisfies KudosRecord;
    })
    .sort(
      (a, b) =>
        b.event.createdAt.localeCompare(a.event.createdAt) || b.event.id.localeCompare(a.event.id),
    );
}

export class ProjectionManager {
  constructor(private readonly storage: KudosStorage) {}

  rebuild(): { generated: string[]; removed: string[] } {
    this.storage.assertWritable();
    const events = this.storage.getEvents();
    const profiles = this.storage.listAgents();
    const records = recordsFromEvents(events);
    const rebuiltAt = events.at(-1)?.createdAt ?? new Date(0).toISOString();
    const generated: string[] = [];

    for (const profile of profiles) {
      const agentDirectory = join(this.storage.home, profile.id);
      assertNoSymlinkEscape(this.storage.home, agentDirectory);
      ensureDirectory(agentDirectory);
      const profilePath = join(agentDirectory, 'profile.json');
      const winsPath = join(agentDirectory, 'WINS.md');
      const notesPath = join(agentDirectory, 'NOTES.md');
      const inboxDirectory = join(agentDirectory, 'inbox');
      assertNoSymlinkEscape(this.storage.home, inboxDirectory);
      ensureDirectory(inboxDirectory);

      atomicWriteDerivedFile(
        profilePath,
        `${JSON.stringify({ _generatedBy: 'agent-kudos', ...profile }, null, 2)}\n`,
      );
      generated.push(manifestPath(this.storage.home, profilePath));
      if (!existsSync(notesPath)) {
        atomicWriteFile(
          notesPath,
          `# Notes — ${profile.displayName}\n\n<!-- Human-owned. Agent Kudos will never overwrite this file. -->\n`,
        );
      }

      const agentRecords = records.filter((record) => record.event.recipientAgentId === profile.id);
      if (this.storage.config.projection.writeWinsMarkdown) {
        atomicWriteDerivedFile(winsPath, winsMarkdown(profile, agentRecords, rebuiltAt));
        generated.push(manifestPath(this.storage.home, winsPath));
      }
      if (this.storage.config.projection.writeInboxEntries) {
        for (const record of agentRecords.filter(
          (item) => item.status === 'unacknowledged' && item.revocationStatus === 'active',
        )) {
          const inboxPath = join(inboxDirectory, `${record.event.id}.md`);
          atomicWriteDerivedFile(inboxPath, inboxMarkdown(record));
          generated.push(manifestPath(this.storage.home, inboxPath));
        }
      }
    }

    const keep = new Set(generated);
    const removed: string[] = [];
    for (const stale of this.storage.projectionManifest()) {
      if (keep.has(stale)) continue;
      const path = join(this.storage.home, stale);
      assertNoSymlinkEscape(this.storage.home, path);
      if (!existsSync(path)) continue;
      const stat = lstatSync(path);
      if (!stat.isFile() || stat.isSymbolicLink()) {
        throw new KudosError('UNSAFE_PATH', `Refusing to remove unsafe generated path: ${stale}`);
      }
      unlinkSync(path);
      removed.push(stale);
    }
    this.storage.replaceProjectionManifest(generated, rebuiltAt);
    return { generated: generated.sort(), removed: removed.sort() };
  }

  syncAgent(agentId: string): { generated: string[]; removed: string[] } {
    this.storage.assertWritable();
    const profile = this.storage.getAgent(agentId);
    if (!profile) throw new KudosError('AGENT_NOT_FOUND', `Unknown agent: ${agentId}`);
    const events = this.storage.getEvents();
    const records = recordsFromEvents(events).filter(
      (record) => record.event.recipientAgentId === profile.id,
    );
    const rebuiltAt = events.at(-1)?.createdAt ?? new Date(0).toISOString();
    const agentDirectory = join(this.storage.home, profile.id);
    const inboxDirectory = join(agentDirectory, 'inbox');
    assertNoSymlinkEscape(this.storage.home, agentDirectory);
    assertNoSymlinkEscape(this.storage.home, inboxDirectory);
    ensureDirectory(agentDirectory);
    ensureDirectory(inboxDirectory);

    const generated: string[] = [];
    const profilePath = join(agentDirectory, 'profile.json');
    atomicWriteDerivedFile(
      profilePath,
      `${JSON.stringify({ _generatedBy: 'agent-kudos', ...profile }, null, 2)}\n`,
    );
    generated.push(manifestPath(this.storage.home, profilePath));

    const notesPath = join(agentDirectory, 'NOTES.md');
    if (!existsSync(notesPath)) {
      atomicWriteFile(
        notesPath,
        `# Notes — ${profile.displayName}\n\n<!-- Human-owned. Agent Kudos will never overwrite this file. -->\n`,
      );
    }

    if (this.storage.config.projection.writeWinsMarkdown) {
      const winsPath = join(agentDirectory, 'WINS.md');
      atomicWriteDerivedFile(winsPath, winsMarkdown(profile, records, rebuiltAt));
      generated.push(manifestPath(this.storage.home, winsPath));
    }

    if (this.storage.config.projection.writeInboxEntries) {
      for (const record of records.filter(
        (item) => item.status === 'unacknowledged' && item.revocationStatus === 'active',
      )) {
        const inboxPath = join(inboxDirectory, `${record.event.id}.md`);
        const relativePath = manifestPath(this.storage.home, inboxPath);
        if (!existsSync(inboxPath)) atomicWriteDerivedFile(inboxPath, inboxMarkdown(record));
        generated.push(relativePath);
      }
    }

    const keep = new Set(generated);
    const prefixes = [`${profile.id}/`, `${profile.id}\\`];
    const removed: string[] = [];
    for (const stale of this.storage
      .projectionManifest()
      .filter((path) => prefixes.some((prefix) => path.startsWith(prefix)))) {
      if (keep.has(stale)) continue;
      const path = join(this.storage.home, stale);
      assertNoSymlinkEscape(this.storage.home, path);
      if (!existsSync(path)) continue;
      const stat = lstatSync(path);
      if (!stat.isFile() || stat.isSymbolicLink()) {
        throw new KudosError('UNSAFE_PATH', `Refusing to remove unsafe generated path: ${stale}`);
      }
      unlinkSync(path);
      removed.push(stale);
    }
    this.storage.replaceAgentProjectionManifest(profile.id, generated, rebuiltAt);
    return { generated: generated.sort(), removed: removed.sort() };
  }

  expectedPaths(): string[] {
    const profiles = this.storage.listAgents();
    const records = recordsFromEvents(this.storage.getReadableEvents());
    const paths: string[] = [];
    for (const profile of profiles) {
      paths.push(`${profile.id}/profile.json`);
      if (this.storage.config.projection.writeWinsMarkdown) paths.push(`${profile.id}/WINS.md`);
      if (this.storage.config.projection.writeInboxEntries) {
        for (const record of records.filter(
          (item) =>
            item.event.recipientAgentId === profile.id &&
            item.status === 'unacknowledged' &&
            item.revocationStatus === 'active',
        )) {
          paths.push(`${profile.id}/inbox/${record.event.id}.md`);
        }
      }
    }
    return paths.sort();
  }
}
